-- Migration manuelle FABOS - votes des créations.
-- À exécuter dans Adminer sur la base fabos, sans doctrine:schema:update --force.

CREATE TABLE IF NOT EXISTS CREATION_VOTE (
    id INT AUTO_INCREMENT NOT NULL,
    creationId INT NOT NULL,
    userId INT NOT NULL,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX IDX_CREATION_VOTE_CREATION (creationId),
    INDEX IDX_CREATION_VOTE_USER (userId),
    UNIQUE INDEX UNIQ_CREATION_VOTE_USER (creationId, userId),
    PRIMARY KEY(id),
    CONSTRAINT FK_CREATION_VOTE_CREATION FOREIGN KEY (creationId) REFERENCES CREATION (id) ON DELETE CASCADE,
    CONSTRAINT FK_CREATION_VOTE_USER FOREIGN KEY (userId) REFERENCES UTILISATEUR (id) ON DELETE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
