CREATE TABLE IF NOT EXISTS CREATION (
    id INT AUTO_INCREMENT NOT NULL,
    title VARCHAR(150) NOT NULL,
    description LONGTEXT DEFAULT NULL,
    imageFilename VARCHAR(255) DEFAULT NULL,
    fileFilename VARCHAR(255) DEFAULT NULL,
    externalUrl VARCHAR(500) DEFAULT NULL,
    authorId INT DEFAULT NULL,
    authorName VARCHAR(150) DEFAULT NULL,
    isPublished TINYINT(1) NOT NULL DEFAULT 1,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME DEFAULT NULL,
    INDEX IDX_CREATION_AUTHOR (authorId),
    INDEX IDX_CREATION_PUBLISHED_CREATED (isPublished, createdAt),
    PRIMARY KEY(id),
    CONSTRAINT FK_CREATION_AUTHOR FOREIGN KEY (authorId) REFERENCES UTILISATEUR (id) ON DELETE SET NULL
) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
