<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/** Phase E target schema. Fresh-V1 model: no compatibility shadow tables. */
final class Version20260810100000 extends AbstractMigration
{
    public function isTransactional(): bool { return false; }
    public function getDescription(): string { return 'Federated identity, public profiles and the versioned FabOS network.'; }

    public function up(Schema $schema): void
    {
        $this->addSql("ALTER TABLE UTILISATEUR ADD publicSlug VARCHAR(80) DEFAULT NULL, ADD publicProfileEnabled TINYINT(1) NOT NULL DEFAULT 0, ADD publicFields JSON DEFAULT NULL, ADD publicBio VARCHAR(500) DEFAULT NULL, ADD UNIQUE INDEX UNIQ_USER_PUBLIC_SLUG (publicSlug)");
        $this->addSql("CREATE TABLE AUTH_PROVIDER (id INT AUTO_INCREMENT NOT NULL, providerKey VARCHAR(80) NOT NULL, label VARCHAR(140) NOT NULL, issuer VARCHAR(255) NOT NULL, clientId VARCHAR(255) NOT NULL, clientSecretEnv VARCHAR(120) NOT NULL, scopes VARCHAR(255) NOT NULL DEFAULT 'openid profile email', enabled TINYINT(1) NOT NULL DEFAULT 1, createdAt DATETIME NOT NULL, UNIQUE INDEX UNIQ_AUTH_PROVIDER_KEY (providerKey), UNIQUE INDEX UNIQ_AUTH_PROVIDER_ISSUER (issuer), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB");
        $this->addSql("CREATE TABLE EXTERNAL_IDENTITY (id INT AUTO_INCREMENT NOT NULL, userId INT NOT NULL, issuer VARCHAR(255) NOT NULL, subject VARCHAR(255) NOT NULL, providerKey VARCHAR(80) NOT NULL, lastClaimsAt DATETIME DEFAULT NULL, revokedAt DATETIME DEFAULT NULL, createdAt DATETIME NOT NULL, INDEX IDX_EXTERNAL_IDENTITY_USER (userId), UNIQUE INDEX UNIQ_EXTERNAL_IDENTITY_SUBJECT (issuer, subject), CONSTRAINT FK_EXTERNAL_IDENTITY_USER FOREIGN KEY (userId) REFERENCES UTILISATEUR (id) ON DELETE CASCADE, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB");
        $this->addSql("CREATE TABLE FABOS_INSTANCE (id INT NOT NULL, instanceUuid CHAR(36) NOT NULL, displayName VARCHAR(140) NOT NULL, canonicalOrigin VARCHAR(255) NOT NULL, activeKeyId VARCHAR(80) NOT NULL, publicKey LONGTEXT NOT NULL, privateKeyEncrypted LONGTEXT NOT NULL, createdAt DATETIME NOT NULL, rotatedAt DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_FABOS_INSTANCE_UUID (instanceUuid), UNIQUE INDEX UNIQ_FABOS_INSTANCE_ORIGIN (canonicalOrigin), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB");
        $this->addSql("CREATE TABLE FABOS_PEER (id INT AUTO_INCREMENT NOT NULL, institutionId INT DEFAULT NULL, instanceUuid CHAR(36) NOT NULL, origin VARCHAR(255) NOT NULL, keyId VARCHAR(80) NOT NULL, publicKey LONGTEXT NOT NULL, trustState VARCHAR(20) NOT NULL DEFAULT 'pending', suspendedAt DATETIME DEFAULT NULL, createdAt DATETIME NOT NULL, UNIQUE INDEX UNIQ_FABOS_PEER_UUID (instanceUuid), UNIQUE INDEX UNIQ_FABOS_PEER_ORIGIN (origin), INDEX IDX_FABOS_PEER_INSTITUTION (institutionId), CONSTRAINT FK_FABOS_PEER_INSTITUTION FOREIGN KEY (institutionId) REFERENCES INSTITUTION (id) ON DELETE SET NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB");
        $this->addSql("CREATE TABLE FABOS_REPLAY (nonceHash CHAR(64) NOT NULL, peerId INT NOT NULL, expiresAt DATETIME NOT NULL, consumedAt DATETIME NOT NULL, INDEX IDX_FABOS_REPLAY_EXPIRY (expiresAt), CONSTRAINT FK_FABOS_REPLAY_PEER FOREIGN KEY (peerId) REFERENCES FABOS_PEER (id) ON DELETE CASCADE, PRIMARY KEY(nonceHash)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB");
        $this->addSql("CREATE TABLE FABOS_EXCHANGE (id INT AUTO_INCREMENT NOT NULL, tokenHash CHAR(64) NOT NULL, userId INT NOT NULL, audienceUuid CHAR(36) NOT NULL, claimsJson JSON NOT NULL, expiresAt DATETIME NOT NULL, consumedAt DATETIME DEFAULT NULL, revokedAt DATETIME DEFAULT NULL, createdAt DATETIME NOT NULL, UNIQUE INDEX UNIQ_FABOS_EXCHANGE_TOKEN (tokenHash), INDEX IDX_FABOS_EXCHANGE_USER (userId), CONSTRAINT FK_FABOS_EXCHANGE_USER FOREIGN KEY (userId) REFERENCES UTILISATEUR (id) ON DELETE CASCADE, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB");
        $this->addSql("CREATE TABLE FEDERATED_CREDENTIAL (id INT AUTO_INCREMENT NOT NULL, userId INT NOT NULL, sourceInstanceUuid CHAR(36) NOT NULL, sourceObjectUuid CHAR(36) NOT NULL, kind VARCHAR(30) NOT NULL, label VARCHAR(255) NOT NULL, payloadJson JSON NOT NULL, issuedAt DATETIME NOT NULL, expiresAt DATETIME DEFAULT NULL, revokedAt DATETIME DEFAULT NULL, importedAt DATETIME NOT NULL, UNIQUE INDEX UNIQ_FEDERATED_CREDENTIAL (userId, sourceInstanceUuid, sourceObjectUuid), INDEX IDX_FEDERATED_CREDENTIAL_USER (userId), CONSTRAINT FK_FEDERATED_CREDENTIAL_USER FOREIGN KEY (userId) REFERENCES UTILISATEUR (id) ON DELETE CASCADE, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB");
        $this->addSql("CREATE TABLE FEDERATED_MACHINE_CATALOG (id INT AUTO_INCREMENT NOT NULL, sourceInstanceUuid CHAR(36) NOT NULL, sourceObjectUuid CHAR(36) NOT NULL, brand VARCHAR(140) NOT NULL, model VARCHAR(180) NOT NULL, payloadJson JSON NOT NULL, archivedAt DATETIME DEFAULT NULL, importedAt DATETIME NOT NULL, UNIQUE INDEX UNIQ_FEDERATED_MACHINE (sourceInstanceUuid, sourceObjectUuid), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB");
        $this->addSql("CREATE TABLE FABOS_NETWORK_AUDIT (id BIGINT AUTO_INCREMENT NOT NULL, peerId INT DEFAULT NULL, action VARCHAR(80) NOT NULL, objectType VARCHAR(50) DEFAULT NULL, objectId VARCHAR(100) DEFAULT NULL, outcome VARCHAR(30) NOT NULL, detailJson JSON DEFAULT NULL, createdAt DATETIME NOT NULL, INDEX IDX_NETWORK_AUDIT_PEER (peerId), INDEX IDX_NETWORK_AUDIT_CREATED (createdAt), CONSTRAINT FK_NETWORK_AUDIT_PEER FOREIGN KEY (peerId) REFERENCES FABOS_PEER (id) ON DELETE SET NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB");
    }

    public function down(Schema $schema): void
    {
        foreach (['FABOS_NETWORK_AUDIT', 'FEDERATED_MACHINE_CATALOG', 'FEDERATED_CREDENTIAL', 'FABOS_EXCHANGE', 'FABOS_REPLAY', 'FABOS_PEER', 'FABOS_INSTANCE', 'EXTERNAL_IDENTITY', 'AUTH_PROVIDER'] as $table) { $this->addSql('DROP TABLE ' . $table); }
        $this->addSql('ALTER TABLE UTILISATEUR DROP publicSlug, DROP publicProfileEnabled, DROP publicFields, DROP publicBio');
    }
}
